server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # --- PROXY INVERSO AL BACKEND ---
    location /api/ {
        # 'backend' es el nombre del servicio en el docker-compose.
        # '8080' es el puerto interno de Spring Boot.
        proxy_pass http://backend:8080;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # --- ENRUTAMIENTO SPA (ANGULAR) ---
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optimización de carga
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}
