export enum ProjectStatus {
  APROBADO = 'APROBADO',
  APROBADO_OBSERVACIONES = 'APROBADO_OBSERVACIONES',
  NO_APROBADO = 'NO_APROBADO',
  EN_REVISION = 'EN_REVISION',
  EN_DESARROLLO = 'EN_DESARROLLO',
  APLAZADO = 'APLAZADO',
  SUSPENDIDO = 'SUSPENDIDO',
  CANCELADO = 'CANCELADO'
}
