import { Injectable } from '@angular/core';
import { Subject } from 'rxjs';

export enum AppEventType {
  // --- Propuestas ---
  PROPOSAL_CREATED = 'PROPOSAL_CREATED',
  EVALUATION_ASSIGNED = 'EVALUATION_ASSIGNED',
  // --- Anteproyecto ---
  PRELIMINARY_DRAFT_CREATED = 'PRELIMINARY_DRAFT_CREATED',
  REVIEWERS_ASSIGNED = 'REVIEWERS_ASSIGNED',
  DOCUMENT_CORRECTION_UPLOADED = 'DOCUMENT_CORRECTION_UPLOADED',
  COUNCIL_RESOLUTION_UPLOADED = 'COUNCIL_RESOLUTION_UPLOADED',
  // --- Trabajos de Grado ---
  THESIS_ADVANCE_UPLOADED = 'THESIS_ADVANCE_UPLOADED',
  THESIS_ADVANCE_EVALUATED = 'THESIS_ADVANCE_EVALUATED',
  THESIS_FINAL_DELIVERY_UPLOADED = 'THESIS_FINAL_DELIVERY_UPLOADED',
  THESIS_SUSTENTATION_PROGRAMMED = 'THESIS_SUSTENTATION_PROGRAMMED',
  THESIS_VERDICT_REGISTERED = 'THESIS_VERDICT_REGISTERED',
  SPECIAL_REQUEST_CREATED = 'SPECIAL_REQUEST_CREATED',
  SPECIAL_REQUEST_RESOLVED = 'SPECIAL_REQUEST_RESOLVED',
  THESIS_PAZ_Y_SALVO_REGISTERED = 'THESIS_PAZ_Y_SALVO_REGISTERED',
  THESIS_CORRECTED_DOCUMENTS_UPLOADED = 'THESIS_CORRECTED_DOCUMENTS_UPLOADED',
  THESIS_CORRESPONDENCE_REGISTERED = 'THESIS_CORRESPONDENCE_REGISTERED',
  THESIS_CORRECTED_DOCUMENTS_EVALUATED = 'THESIS_CORRECTED_DOCUMENTS_EVALUATED'
}

export interface AppEvent {
  type: AppEventType;
  payload: any
}

@Injectable({
  providedIn: 'root'
})
export class EventBusService {
  private readonly eventSubject = new Subject<AppEvent>();
  events$ = this.eventSubject.asObservable();
  emit(event: AppEvent){
    this.eventSubject.next(event);
  }
}
